### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by jourmore** [TurtleTools/portein#1]
portein 7lc2 7lc2.png
---------"Missing output directives.”

from portein import plot_portrait, PorteinConfig
config = PorteinConfig.default()
config.helix.as_cylinder = True # Plot helices as cylinders
config.sheet.color = "red"
config.sheet.opacity = 0.5
plot_portrait("7lc2", config, height=12)
---------"PDB file for 7lc2 could not be downloaded."

**Comment by Ninjani** [comment]
Can you try with the new version? The command is now `portein secondary 7lc2`

**Comment by jourmore** [comment]
> Can you try with the new version? The command is now `portein secondary 7lc2`

Thanks very much！
